/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { XAIBOT } from "./XAIBOT";
export * as factories from "./factories";
export { XAIBOT__factory } from "./factories/XAIBOT__factory";
